### ISSUE TITLE
lots of undefined variables in Sass

### ISSUE THREAD

**Issue by 1stevengrant** [laraform/laraform-laravel#1]
After including `@import '~@laraform/laraform/src/themes/bs4/scss/theme.scss';`

in my Sass file, there's a lot of undefined variables. Obviously I could go through and define those variables manually but would have thought the theme would have them defined?

**Comment by laraform** [comment]
Hi! If you are using Bootstrap 4 you should import this scss after you’ve imported the Bootstrap 4 variables. Otherwise just import the default theme which does not rely on any CSS framework variables:
@laraform/laraform/src/themes/default/scss/theme.scss
